# -*- coding: utf-8 -*-
"""data-analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rC5H8B0p-v6cxhTBi1nik3FDFWPnbzGT

Dados entre 2014 e 2021 (todos)

---
"""

names <- c("horario", "temp", "vento", "umid", "sensa")
con <- url("http://ic.unicamp.br/~zanoni/cepagri/cepagri.csv")
cepagri <- read.csv('./cepagri.csv', header = FALSE, sep = ";", col.names = names)

cepagri

"""Dados entre 2015 e 2020

---


"""

horariosValidos = cepagri[as.Date(cepagri$horario, format='%d/%m/%Y') > as.Date('31/12/2014', format='%d/%m/%Y') & as.Date(cepagri$horario, format='%d/%m/%Y') < as.Date('01/01/2021', format='%d/%m/%Y'), ]

horariosValidos

"""Tabela: Temperatura média entre 2014 e 2020"""

library(ggplot2)

getDadosPorAno <- function (ano){
  cepagri[as.Date(cepagri$horario, format='%d/%m/%Y') > as.Date(paste(c('31/12/', ano - 1), collapse= ''), format='%d/%m/%Y') & as.Date(cepagri$horario, format='%d/%m/%Y') < as.Date(paste(c('01/01/', ano + 1), collapse= ''), format='%d/%m/%Y') , ]
}

mediaTemperaturaPorAno <- function (ano){
  dadosDoAno = getDadosPorAno(ano)
  valores = dadosDoAno$temp

  soma = 0

  for (i in valores){
    if (!is.na(i) & i != ' [ERRO]')
      soma = soma + as.double(i)
  }

  soma / length(valores)
}

mediaTemperaturaPorIntervalo <- function (intervalo) {
  medias = c()

  for (ano in intervalo) {
    mediaDoAno = mediaTemperaturaPorAno(ano)
    medias = append(medias, mediaDoAno)
  }

  medias
}

ano = c('2014', '2015', '2016', '2017', '2018', '2019', '2020')
media = mediaTemperaturaPorIntervalo(c(2014, 2015, 2016, 2017, 2018, 2019, 2020))

df = data.frame(ano, media)

df

"""Gráfico: Temperatura média entre 2014 e 2020"""

ggplot() + geom_bar(data = df, aes(x = ano, y = media),
                    stat = "identity") + ggtitle("Temperatura média / ano")